### ISSUE TITLE
Makefile wants to install templates that aren't in repo

### ISSUE THREAD

**Issue by jeanconn** [sot/twiki-wg#1]
Looks like these files need to be added:

ssawg_index.html mpcwg_index.html twg_index.html

**Comment by taldcroft** [comment]
Closed by cd61d59.

**Comment by taldcroft** [comment]
Actually that might not be the right thing to do.  Stand by.

**Comment by jeanconn** [comment]
Not time critical because (while I didn't try to understand if they are templates or source or whatever), these files are already in SKA/data/twiki-wg.  So I just did the other part of the Makefile install (copying the script to ska3/flight/share/) as the aca user.

**Comment by taldcroft** [comment]
OK, force pushed cea1720.
