### ISSUE TITLE
SSAWG Scraper - Fix Relative Links / Rate Noise Trending Header Missing

### ISSUE THREAD

**Issue by johnny1up** [sot/twiki-wg#6]
Bugs found in ssawg_trending_scraper.py, from on the March 11, 2020 SSAWG:

- OBC Rate Noise Trending title is missing (currently, pitch header is in its place)
- OBC Rate Noise Trending description is missing
- All non-URL links are relative (e.g. tables and FSS Performance "presense (sic) and alpha trending" link).

**Comment by taldcroft** [comment]
Fixed by #7
