### ISSUE TITLE
SSAWG scraper - dealing with the number of ID'd stars plot

### ISSUE THREAD

**Issue by taldcroft** [sot/twiki-wg#8]
I think the best way to deal with this thorn is to make a new trending block dedicated to that plot (e.g. https://cxc.harvard.edu/mta/ASPECT/acq_stat_reports/2020/Q2/id_acq_stars.png) and always take it from the latest available quarter instead of one with at least 50% of data.

**Comment by johnny1up** [comment]
I can do that.

**Comment by jeanconn** [comment]
OK.  That's probably faster than me coming back to the acquisition report pages and making a new primary page for this plot.

**Comment by taldcroft** [comment]
Closed by recent PRs.
